update dotfiles

diff --git a/.local/bin/ultimate-push b/.local/bin/ultimate-push
--- a/.local/bin/ultimate-push
+++ b/.local/bin/ultimate-push
@@ -38,8 +38,8 @@ echo "Pushing"
 echo ""
 
 echo " backing up group and hist files"
-sudo cat /etc/group > ~/group.bak && echo "group backup successful" || echo " 🗶  group backup failed"
-cat ~/.zsh_history > ~/.zsh_history.bak && echo "hist backup successful" || echo " 🗶  hist backup failed"
+sudo cat /etc/group > ~/group.bak && echo " group backup successful" || echo " 🗶  group backup failed"
+cat ~/.zsh_history > ~/.zsh_history.bak && echo " hist backup successful" || echo " 🗶  hist backup failed"
 
 echo " ✅✅✅"
 
